upload:
	cp ~/.emacs .
	cp ~/.bashrc .
	cp ~/.gitconfig .
	cp ~/.inputrc .
	cp ~/.profile .
	cp -r ~/.emacs.d .

install:
	cp .emacs ~/
	cp .bashrc ~/
	cp .gitconfig ~/
	cp .inputrc ~/
	cp .profile ~/
	cp -r .emacs.d ~/